---
- name: Add EPEL repository.
  when: ansible_os_family == "RedHat"
  yum_repository:
      name: epel
      description: EPEL YUM repo
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      state: present

- name: Install Icecast.
  package:
      name: "{{ icecast_package }}"
      state: present

- name: Create systemd service.
  template:
      src: icecast.service.j2
      dest: /etc/systemd/system/{{ icecast_package }}.service
      owner: root
      group: root
      mode: '600'
  notify: Reload Icecast.

