---
- name: Load OS-specific variables.
  include_vars:
      file: "{{ ansible_facts.os_family }}.yaml"

- name: Install Icecast.
  import_tasks: "install.yaml"

- name: Configure Icecast.
  import_tasks: "configure.yaml"
